### ISSUE TITLE
Not able to paste

### ISSUE THREAD

**Issue by TurboCheetah** [PrivateBin/docker-nginx-fpm-alpine#2]
When deploying using docker-compose, I am unable to paste.
`docker-compose.yml`
```services:
  privatebin:
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine
    restart: unless-stopped
    ports:
    - 8083:80
    volumes:
      - ./data:/srv/data
version: "3.4"
```
Error: From PrivateBin WebUI: `Could not create paste: server error or not responding`
From logs:
```NOTICE: PHP message: PHP Fatal error:  Uncaught Exception: unable to write to file /srv/data/.htaccess in /srv/lib/Persistence/AbstractPersistence.php:99
Stack trace:
#0 /srv/lib/Persistence/AbstractPersistence.php(72): PrivateBin\Persistence\AbstractPersistence::_initialize()
#1 /srv/lib/Persistence/TrafficLimiter.php(104): PrivateBin\Persistence\AbstractPersistence::_exists('traffic_limiter...')
#2 /srv/lib/Controller.php(200): PrivateBin\Persistence\TrafficLimiter::canPass()
#3 /srv/lib/Controller.php(125): PrivateBin\Controller->_create()
#4 /var/www/index.php(18): PrivateBin\Controller->__construct()
#5 {main}
  thrown in /srv/lib/Persistence/AbstractPersistence.php on line 99
2019/02/07 00:28:29 [error] 9#9: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: unable to write to file /srv/data/.htaccess in /srv/lib/Persistence/AbstractPersistence.php:99
Stack trace:
#0 /srv/lib/Persistence/AbstractPersistence.php(72): PrivateBin\Persistence\AbstractPersistence::_initialize()
#1 /srv/lib/Persistence/TrafficLimiter.php(104): PrivateBin\Persistence\AbstractPersistence::_exists('traffic_limiter...')
#2 /srv/lib/Controller.php(200): PrivateBin\Persistence\TrafficLimiter::canPass()
#3 /srv/lib/Controller.php(125): PrivateBin\Controller->_create()
#4 /var/www/index.php(18): PrivateBin\Controller->__construct()
#5 {main}
  thrown in /srv/lib/Persistence/AbstractPersistence.php on line 99" while reading response header from upstream, client: 172.30.0.1, server: , request: "POST / HTTP/1.0", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "localhost:8083"
```
EDIT: Formatting

**Comment by elrido** [comment]
That means the data folder isn't writeable, so the traffic limiter file (and other files generated on the first start) can't be created. This is usually a permission problem.

You make that folder world writeable (chmod o+rwx [path/to/data],  outside of the container on your host), then you access the site so the files get initiated and then look what UID and GID the files got created as. Finally you can hand over ownership of the data folder to these two IDs (chown [UID]:[GID] [path/to/data]) and revoke the world access (chmod o-rwx [path/to/data]).
