### ISSUE TITLE
Unable to create a paste

### ISSUE THREAD

**Issue by Binternet** [PrivateBin/docker-nginx-fpm-alpine#22]
While trying to create a new paste I'm encountering the following error:

`Could not create paste: server error or not responding`

`
2020/08/10 20:33:23 [error] 198#198: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: unable to write to file /srv/data/.htaccess in /srv/lib/Persistence/AbstractPersistence.php:99
Stack trace:
#0 /srv/lib/Persistence/AbstractPersistence.php(72): PrivateBin\Persistence\AbstractPersistence::_initialize()
#1 /srv/lib/Persistence/TrafficLimiter.php(104): PrivateBin\Persistence\AbstractPersistence::_exists('traffic_limiter...')
#2 /srv/lib/Controller.php(201): PrivateBin\Persistence\TrafficLimiter::canPass()
#3 /srv/lib/Controller.php(125): PrivateBin\Controller->_create()
#4 /var/www/index.php(18): PrivateBin\Controller->__construct()
#5 {main}
  thrown in /srv/lib/Persistence/AbstractPersistence.php on line 99" while reading response header from upstream, client: 172.17.0.1, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:"
`

I know its probably a permission error, but I ran the docker image exactly as the documentation says:

`
docker run -d
--restart="always"
--read-only 
-p 8080:8080 
-v /opt/privatebin/code/data:/srv/data 
privatebin/nginx-fpm-alpine
`

**Comment by Binternet** [comment]
OK found this:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/2
